language: java

sudo: enabled

before_install:
	-echo "Hello world shashi in the before install"
  	-sudo apt-get -qq update

install:
	- echo "Hello world shashi in the install"

script:	
	echo "In the script part of the codeshashi "
	ls -l
	- bundle exec rake build
	- bundle exec rake builddoc

before_script:
	echo "In the before script of the code shashi"	
	
