language: python

python:
  - "2.7"
  - "3.4"
services: 
  - mongodb
install: # command to install dependencies
  - "pip install -r requirements.txt"
  - ls -l

# command to run tests
script: python test.py


sudo: false
