language: python

sudo: enabled


before_install:
	echo "Hello world shashi in the before install"
	ls -l

install:
	echo "Hello world shashi in the install"
	ls -l 
	echo "In the Install section of the code shashi"

script:	
	echo "In the script part of the codeshashi "
	ls -l

before_script:
	echo "In the before script of the code shashi"	
	ls -pl	
	
